#!/bin/sh

# This script is to start and stop sigma CA and DUT service.
npu_topology=$(get_wifi_config global npu)
security_path=/mnt/jffs2

if [ $npu_topology == "1" ]; then
	if [ ! -f ${security_path}/npu_cfg ]; then
		cp -f /scripts/npu_cfg ${security_path}/npu_cfg
	fi
	source ${security_path}/npu_cfg
fi

kill_process() {
        pid_name=$1
        pid=`ps | grep "$pid_name" | grep -v "grep $name" | awk '{print $1}'`
        # Checking pid is empty
        if [ -n "$pid" ]; then
        kill $pid
        fi
}

start() {
	export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/scripts:/usr/local/sbin/:/usr/local/bin
	export LD_LIBRARY_PATH=/lib:/usr/lib

	if [ -f /usr/bin/qtn_dut ] ; then

		echo "Starting sigma DUT"
		if [ "$npu_topology" == "1" ]; then
			[ -f /scripts/npu_setup ] && . npu_setup
			qtn_dut -i lo -p WFA_DUT_PORT_PLACEHOLDER -l 7 -b $host_bridge_ip -m $host_bridge_mac -n $npu_topology &
		else
			qtn_dut -i lo -p WFA_DUT_PORT_PLACEHOLDER -l 7 &
		fi

		echo "Starting sigma CA"
		## have to wait a bit to make sure that qtn_dut is started
		sleep 5
		qtn_ca -i br0 -p WFA_CA_PORT_PLACEHOLDER -I 127.0.0.1 -P WFA_DUT_PORT_PLACEHOLDER -l 7 &
	fi
}

stop() {
        echo "Stopping qtn_dut"
        kill_process "qtn_dut"

	echo "Stopping qtn_ca"
	kill_process "qtn_ca"
}

restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
