/* autogenerated */

#define MUC_TX_STATS_NAMES_TABLE { \
	"bcn_enq_failed", \
	"bcn_queue_full", \
	"tx_status_set", \
	"host_intr", \
	"tx_reserved", \
	"tx_reserve_fail", \
	"txalert_mu_ndp_update", \
	"txalert_mu_rpt_poll", \
	"txalert_mu_queue_full", \
	"txalert_mu_queue_fail", \
	"sample_rate_mu", \
	"sample_bw_mu", \
	"txdone_intr", \
	"txalert_intr", \
	"txalert_tasklet", \
	"txalert_bcn_update", \
	"txalert_ndp_update", \
	"tx_ndp_q_occupied", \
	"tx_ndp_start", \
	"tx_pwr", \
	"bcn_scheme_power_save", \
	"bcn_scheme", \
	"fd_acquire", \
	"fd_release", \
	"fd_acq_fail", \
	"fd_acq_fail_frms", \
	"fd_acq_hal_fail", \
	"fd_acq_hal_fail_frms", \
	"ba_send", \
	"fd_free_nodeclean", \
	"tx_restrict_probe", \
	"tx_restrict_mode", \
	"tx_restrict_delay", \
	"tx_sample_pkts", \
	"tx_sample_bytes", \
	"tx_underflow", \
	"tx_hal_enqueued", \
	"txbf_mode", \
	"txbf_subf_to_defmat", \
	"psel_matrix", \
	"sample_rate", \
	"sample_bw", \
	"ra_flags", \
	"fd_balance", \
	"invalid_delay", \
	"halt_tx", \
	"resume_tx", \
	"rfctrl_on", \
	"rfctrl_off", \
	"go_offchan", \
	"go_datachan", \
	"defer_cc", \
	"deferred_cc_done", \
	"off_chan_sample", \
	"off_chan_scan", \
	"off_chan_cac", \
	"cca_pri", \
	"cca_sec", \
	"cca_sec40", \
	"cca_busy", \
	"cca_fat", \
	"cca_intf", \
	"cca_trfc", \
	"cca_tx_usec", \
	"mu_prec_snd_tx", \
	"mu_prec_snd_wait_done", \
	"mu_grp_sel_snd_tx", \
	"mu_grp_sel_snd_wait_done", \
	"oc_auctx_timeout", \
	"oc_auctx_overwrite", \
	"oc_auctx_fail", \
	"gi_cnt", \
	"gi_ncidx", \
	"gi_val", \
	"select_state_ncidx", \
	"select_state_val", \
	"pppc_scale_cnt", \
	"pppc_scale_ncidx", \
	"pppc_scale_val", \
	"pppc_scale_last_gput", \
	"pppc_scale_last_gput_idx", \
	"pppc_scale_base_cnt", \
	"pppc_scale_base_20m", \
	"pppc_scale_base_40m", \
	"pppc_scale_base_80m", \
	"pppc_scale_base_copy", \
	"pppc_scale_overstep", \
	"pppc_scale_rollback", \
	"pppc_0_gput", \
	"tx_max_power", \
	"nc_csr_read_count", \
	"nc_csr_write_count", \
	"nc_csr_done_watermark", \
	"nc_csr_watermark_count", \
	"auc_dtim_notify", \
	"auc_ps_notify", \
	"tx_beacon_done", \
	"sfs_peer_rts", \
	"sfs_peer_rts_flags", \
	"sfs_local_rts", \
	"sfs_local_rts_flags", \
	"sfs_dyn_wmm", \
	"sfs_dyn_wmm_flags", \
	"auc_wmm_ps_notify", \
	"tx_wmm_ps_null_frames", \
	"qtn_bcn_stop", \
	"mu_grp_snd_queue_is_not_empty", \
	"mu_prec_snd_queue_is_not_empty", \
	"mu_group_delete", \
	"mu_group_install", \
	"mu_group_rate_node_updates", \
	"mu_update_rates_mu", \
	"mu_update_rates_su", \
	"autocs_sample_bits", \
	"autocs_adjust_bits", \
	"autocs_step_size", \
	"autocs_cs_thresh", \
	"autocs_min_rssi", \
	"bmps_null_tx_success", \
	"bmps_null_tx_fail", \
	"bmps_null_tx_timeout", \
	"txqueue_g1q0_deadline_frozen", \
	"auc_ipc_retry", \
	"auc_ipc_hwm", \
	"auc_ipc_send_delay", \
	"auc_ipc_send_delay_hwm", \
	"robust_csa_tx_success", \
	"robust_csa_tx_fail", \
}

enum muc_stats_tx_type {
	MUC_STATS_TX_TYPE_BCN_ENQ_FAILED, 
	MUC_STATS_TX_TYPE_BCN_QUEUE_FULL, 
	MUC_STATS_TX_TYPE_TX_STATUS_SET, 
	MUC_STATS_TX_TYPE_HOST_INTR, 
	MUC_STATS_TX_TYPE_TX_RESERVED, 
	MUC_STATS_TX_TYPE_TX_RESERVE_FAIL, 
	MUC_STATS_TX_TYPE_TXALERT_MU_NDP_UPDATE, 
	MUC_STATS_TX_TYPE_TXALERT_MU_RPT_POLL, 
	MUC_STATS_TX_TYPE_TXALERT_MU_QUEUE_FULL, 
	MUC_STATS_TX_TYPE_TXALERT_MU_QUEUE_FAIL, 
	MUC_STATS_TX_TYPE_SAMPLE_RATE_MU, 
	MUC_STATS_TX_TYPE_SAMPLE_BW_MU, 
	MUC_STATS_TX_TYPE_TXDONE_INTR, 
	MUC_STATS_TX_TYPE_TXALERT_INTR, 
	MUC_STATS_TX_TYPE_TXALERT_TASKLET, 
	MUC_STATS_TX_TYPE_TXALERT_BCN_UPDATE, 
	MUC_STATS_TX_TYPE_TXALERT_NDP_UPDATE, 
	MUC_STATS_TX_TYPE_TX_NDP_Q_OCCUPIED, 
	MUC_STATS_TX_TYPE_TX_NDP_START, 
	MUC_STATS_TX_TYPE_TX_PWR, 
	MUC_STATS_TX_TYPE_BCN_SCHEME_POWER_SAVE, 
	MUC_STATS_TX_TYPE_BCN_SCHEME, 
	MUC_STATS_TX_TYPE_FD_ACQUIRE, 
	MUC_STATS_TX_TYPE_FD_RELEASE, 
	MUC_STATS_TX_TYPE_FD_ACQ_FAIL, 
	MUC_STATS_TX_TYPE_FD_ACQ_FAIL_FRMS, 
	MUC_STATS_TX_TYPE_FD_ACQ_HAL_FAIL, 
	MUC_STATS_TX_TYPE_FD_ACQ_HAL_FAIL_FRMS, 
	MUC_STATS_TX_TYPE_BA_SEND, 
	MUC_STATS_TX_TYPE_FD_FREE_NODECLEAN, 
	MUC_STATS_TX_TYPE_TX_RESTRICT_PROBE, 
	MUC_STATS_TX_TYPE_TX_RESTRICT_MODE, 
	MUC_STATS_TX_TYPE_TX_RESTRICT_DELAY, 
	MUC_STATS_TX_TYPE_TX_SAMPLE_PKTS, 
	MUC_STATS_TX_TYPE_TX_SAMPLE_BYTES, 
	MUC_STATS_TX_TYPE_TX_UNDERFLOW, 
	MUC_STATS_TX_TYPE_TX_HAL_ENQUEUED, 
	MUC_STATS_TX_TYPE_TXBF_MODE, 
	MUC_STATS_TX_TYPE_TXBF_SUBF_TO_DEFMAT, 
	MUC_STATS_TX_TYPE_PSEL_MATRIX, 
	MUC_STATS_TX_TYPE_SAMPLE_RATE, 
	MUC_STATS_TX_TYPE_SAMPLE_BW, 
	MUC_STATS_TX_TYPE_RA_FLAGS, 
	MUC_STATS_TX_TYPE_FD_BALANCE, 
	MUC_STATS_TX_TYPE_INVALID_DELAY, 
	MUC_STATS_TX_TYPE_HALT_TX, 
	MUC_STATS_TX_TYPE_RESUME_TX, 
	MUC_STATS_TX_TYPE_RFCTRL_ON, 
	MUC_STATS_TX_TYPE_RFCTRL_OFF, 
	MUC_STATS_TX_TYPE_GO_OFFCHAN, 
	MUC_STATS_TX_TYPE_GO_DATACHAN, 
	MUC_STATS_TX_TYPE_DEFER_CC, 
	MUC_STATS_TX_TYPE_DEFERRED_CC_DONE, 
	MUC_STATS_TX_TYPE_OFF_CHAN_SAMPLE, 
	MUC_STATS_TX_TYPE_OFF_CHAN_SCAN, 
	MUC_STATS_TX_TYPE_OFF_CHAN_CAC, 
	MUC_STATS_TX_TYPE_CCA_PRI, 
	MUC_STATS_TX_TYPE_CCA_SEC, 
	MUC_STATS_TX_TYPE_CCA_SEC40, 
	MUC_STATS_TX_TYPE_CCA_BUSY, 
	MUC_STATS_TX_TYPE_CCA_FAT, 
	MUC_STATS_TX_TYPE_CCA_INTF, 
	MUC_STATS_TX_TYPE_CCA_TRFC, 
	MUC_STATS_TX_TYPE_CCA_TX_USEC, 
	MUC_STATS_TX_TYPE_MU_PREC_SND_TX, 
	MUC_STATS_TX_TYPE_MU_PREC_SND_WAIT_DONE, 
	MUC_STATS_TX_TYPE_MU_GRP_SEL_SND_TX, 
	MUC_STATS_TX_TYPE_MU_GRP_SEL_SND_WAIT_DONE, 
	MUC_STATS_TX_TYPE_OC_AUCTX_TIMEOUT, 
	MUC_STATS_TX_TYPE_OC_AUCTX_OVERWRITE, 
	MUC_STATS_TX_TYPE_OC_AUCTX_FAIL, 
	MUC_STATS_TX_TYPE_GI_CNT, 
	MUC_STATS_TX_TYPE_GI_NCIDX, 
	MUC_STATS_TX_TYPE_GI_VAL, 
	MUC_STATS_TX_TYPE_SELECT_STATE_NCIDX, 
	MUC_STATS_TX_TYPE_SELECT_STATE_VAL, 
	MUC_STATS_TX_TYPE_PPPC_SCALE_CNT, 
	MUC_STATS_TX_TYPE_PPPC_SCALE_NCIDX, 
	MUC_STATS_TX_TYPE_PPPC_SCALE_VAL, 
	MUC_STATS_TX_TYPE_PPPC_SCALE_LAST_GPUT, 
	MUC_STATS_TX_TYPE_PPPC_SCALE_LAST_GPUT_IDX, 
	MUC_STATS_TX_TYPE_PPPC_SCALE_BASE_CNT, 
	MUC_STATS_TX_TYPE_PPPC_SCALE_BASE_20M, 
	MUC_STATS_TX_TYPE_PPPC_SCALE_BASE_40M, 
	MUC_STATS_TX_TYPE_PPPC_SCALE_BASE_80M, 
	MUC_STATS_TX_TYPE_PPPC_SCALE_BASE_COPY, 
	MUC_STATS_TX_TYPE_PPPC_SCALE_OVERSTEP, 
	MUC_STATS_TX_TYPE_PPPC_SCALE_ROLLBACK, 
	MUC_STATS_TX_TYPE_PPPC_0_GPUT, 
	MUC_STATS_TX_TYPE_TX_MAX_POWER, 
	MUC_STATS_TX_TYPE_NC_CSR_READ_COUNT, 
	MUC_STATS_TX_TYPE_NC_CSR_WRITE_COUNT, 
	MUC_STATS_TX_TYPE_NC_CSR_DONE_WATERMARK, 
	MUC_STATS_TX_TYPE_NC_CSR_WATERMARK_COUNT, 
	MUC_STATS_TX_TYPE_AUC_DTIM_NOTIFY, 
	MUC_STATS_TX_TYPE_AUC_PS_NOTIFY, 
	MUC_STATS_TX_TYPE_TX_BEACON_DONE, 
	MUC_STATS_TX_TYPE_SFS_PEER_RTS, 
	MUC_STATS_TX_TYPE_SFS_PEER_RTS_FLAGS, 
	MUC_STATS_TX_TYPE_SFS_LOCAL_RTS, 
	MUC_STATS_TX_TYPE_SFS_LOCAL_RTS_FLAGS, 
	MUC_STATS_TX_TYPE_SFS_DYN_WMM, 
	MUC_STATS_TX_TYPE_SFS_DYN_WMM_FLAGS, 
	MUC_STATS_TX_TYPE_AUC_WMM_PS_NOTIFY, 
	MUC_STATS_TX_TYPE_TX_WMM_PS_NULL_FRAMES, 
	MUC_STATS_TX_TYPE_QTN_BCN_STOP, 
	MUC_STATS_TX_TYPE_MU_GRP_SND_QUEUE_IS_NOT_EMPTY, 
	MUC_STATS_TX_TYPE_MU_PREC_SND_QUEUE_IS_NOT_EMPTY, 
	MUC_STATS_TX_TYPE_MU_GROUP_DELETE, 
	MUC_STATS_TX_TYPE_MU_GROUP_INSTALL, 
	MUC_STATS_TX_TYPE_MU_GROUP_RATE_NODE_UPDATES, 
	MUC_STATS_TX_TYPE_MU_UPDATE_RATES_MU, 
	MUC_STATS_TX_TYPE_MU_UPDATE_RATES_SU, 
	MUC_STATS_TX_TYPE_AUTOCS_SAMPLE_BITS, 
	MUC_STATS_TX_TYPE_AUTOCS_ADJUST_BITS, 
	MUC_STATS_TX_TYPE_AUTOCS_STEP_SIZE, 
	MUC_STATS_TX_TYPE_AUTOCS_CS_THRESH, 
	MUC_STATS_TX_TYPE_AUTOCS_MIN_RSSI, 
	MUC_STATS_TX_TYPE_BMPS_NULL_TX_SUCCESS, 
	MUC_STATS_TX_TYPE_BMPS_NULL_TX_FAIL, 
	MUC_STATS_TX_TYPE_BMPS_NULL_TX_TIMEOUT, 
	MUC_STATS_TX_TYPE_TXQUEUE_G1Q0_DEADLINE_FROZEN, 
	MUC_STATS_TX_TYPE_AUC_IPC_RETRY, 
	MUC_STATS_TX_TYPE_AUC_IPC_HWM, 
	MUC_STATS_TX_TYPE_AUC_IPC_SEND_DELAY, 
	MUC_STATS_TX_TYPE_AUC_IPC_SEND_DELAY_HWM, 
	MUC_STATS_TX_TYPE_ROBUST_CSA_TX_SUCCESS, 
	MUC_STATS_TX_TYPE_ROBUST_CSA_TX_FAIL, 
};

#define MUC_RX_STATS_NAMES_TABLE { \
	"rxdesc_pop_from_host", \
	"rxdesc_get_from_queue", \
	"rxdesc_push_to_host", \
	"rxdesc_non_aggr_push_to_host", \
	"rxdesc_flush_to_host", \
	"rxdesc_reuse_push", \
	"rxdesc_reuse_pop", \
	"rxdesc_status_bad_dur", \
	"rxdesc_status_bad_len", \
	"rxdesc_status_crc_err", \
	"rxdesc_status_cmic_err", \
	"rxdesc_status_cmic_no_crc_err", \
	"rxdesc_status_retry", \
	"agg_stored", \
	"agg_duplicate", \
	"accel_mpdu", \
	"accel_msdu", \
	"accel_fwt_lu_timeout", \
	"accel_mcast_send", \
	"accel_mcast_drop", \
	"accel_no_match", \
	"accel_drop", \
	"accel_err", \
	"rate_train_chk", \
	"rate_train_err", \
	"rate_train_delay", \
	"rate_train_none", \
	"rate_train_hash_bad", \
	"rate_train_hash_good", \
	"agg_oldpkts", \
	"agg_very_oldpkts", \
	"agg_evict_in_order", \
	"agg_evict_in_move", \
	"agg_evict_empty", \
	"agg_timeout", \
	"agg_rxwin_reset", \
	"rx_qnum_err", \
	"rx_mgmt", \
	"rx_ctrl", \
	"rx_pspoll", \
	"rx_pwr_mgmt", \
	"rx_delba", \
	"rx_pwr_mgmt_set", \
	"rx_pwr_mgmt_reset", \
	"rx_desc_underflow", \
	"rx_desc_linkerr", \
	"rx_notify", \
	"rx_df_numelems", \
	"last_recv_seq", \
	"rx_node_not_found", \
	"rx_duplicate", \
	"rx_11n_ndp", \
	"rx_11ac_ndp", \
	"rx_ndp_inv_slot", \
	"rx_ndp_inv_bw", \
	"rx_11n_ndp_no_capt", \
	"rx_ndp_sw_processed", \
	"rx_ndp_lockup", \
	"rx_11n_bf_act", \
	"rx_11ac_bf_act", \
	"rx_bf_act_inv_slot", \
	"rx_csi_data_processed", \
	"rx_csi_data_no_capt", \
	"rx_csi_data_unlock", \
	"rx_csi_jiff_unlock", \
	"rx_amsdu", \
	"rx_data", \
	"prev_rx_data", \
	"rx_recv_qnull", \
	"rx_recv_act", \
	"rx_recv_bcn", \
	"rx_recv_auth", \
	"rx_recv_assoc_req", \
	"rx_recv_assoc_res", \
	"rx_recv_deauth", \
	"rx_recv_disassoc", \
	"rx_mcs_gt_76", \
	"tkip_keys", \
	"rx_tkip_mic_err", \
	"icv_errs", \
	"tmic_errs", \
	"cmic_errs", \
	"crc_errs", \
	"plcp_errs", \
	"ba_tx", \
	"ba_rx", \
	"ba_rx_fail", \
	"sec_oflow", \
	"str_oflow", \
	"oflow_fixup_timeout", \
	"rxdone_intr", \
	"rxtypedone_intr", \
	"ipc_a2m_intr", \
	"tqe_intr", \
	"tqe_in_port_lhost", \
	"tqe_in_port_bad", \
	"tqe_a2m_type_txfb", \
	"tqe_a2m_type_rxpkt", \
	"tqe_a2m_type_unknown", \
	"tqe_reschedule_task", \
	"tqe_desc_unowned", \
	"bb_intr", \
	"bb_irq_dleaf_oflow", \
	"bb_irq_leaf_uflow", \
	"bb_irq_leaf_ldpc_uflow", \
	"bb_irq_tx_td_oflow_intr", \
	"bb_irq_tx_td_uflow_intr", \
	"bb_irq_rx_sm_wdg_intr", \
	"bb_irq_rx_long_dur", \
	"bb_irq_rx_long_dur_11ac", \
	"bb_irq_rx_long_dur_11n", \
	"bb_irq_rx_long_dur_11n_qtn", \
	"bb_irq_rx_sym_exceed_rst", \
	"bb_irq_tx_sm_wdg_intr", \
	"bb_irq_main_sm_wdg_intr", \
	"bb_irq_hready_wdg_intr", \
	"mac_irq_rx_sec_buff_oflow", \
	"mac_irq_rx_strq_oflow", \
	"mac_irq_rx_bb_uflow_intr", \
	"mac_irq_rx_bb_oflow_intr", \
	"bb_irq_hready_wdg_reset", \
	"sreset_wdg_begin", \
	"sreset_wdg_end", \
	"sreset_wdg_in_place", \
	"sreset_wdg_tx_beacon_hang", \
	"sreset_wdg_tx_hang", \
	"sreset_wdg_tx_hang_sec_cca", \
	"sreset_wdg_pm_corrupt", \
	"sreset_wdg_tcm_corrupt", \
	"sreset_wdg_rx_done", \
	"sreset_wdg_in_place_try", \
	"sreset_wdg_tasklet_sched_1", \
	"sreset_wdg_tasklet_sched_2", \
	"sreset_tasklet_sched", \
	"sreset_tasklet_begin", \
	"sreset_tasklet_end", \
	"hreset_req", \
	"sreset_begin", \
	"sreset_end", \
	"sreset_dma_rx_inprog", \
	"sreset_dma_tx_inprog", \
	"sreset_dma_rx_max_wait", \
	"sreset_dma_tx_max_wait", \
	"sreset_dma_tx_hang", \
	"sreset_dma_rx_hang", \
	"sreset_dma_rx_wait_timeout", \
	"sreset_dma_tx_wait_timeout", \
	"sreset_drop_not_valid", \
	"sreset_drop_bad_addr", \
	"rf_cmpvtune_out", \
	"rf_cal_freq", \
	"ac_max", \
	"ac_min", \
	"ac_cur", \
	"ac_adj", \
	"rx_gain", \
	"rd_cache_indx", \
	"logger_sreset_wmac1_dma_rx_inprog", \
	"logger_sreset_wmac1_dma_tx_inprog", \
	"logger_sreset_wmac1_dma_rx_max_wait", \
	"logger_sreset_wmac1_dma_tx_max_wait", \
	"logger_sreset_wmac1_dma_tx_hang", \
	"logger_sreset_wmac1_dma_rx_hang", \
	"logger_sreset_wmac1_dma_rx_wait_timeout", \
	"logger_sreset_wmac1_dma_tx_wait_timeout", \
	"mu_rx_pkt", \
	"pduty_sleep", \
	"pduty_rxoff", \
	"pduty_period", \
	"pduty_pct", \
	"soft_ring_push_to_tqe", \
	"soft_ring_empty", \
	"soft_ring_not_empty", \
	"soft_ring_add_force", \
	"soft_ring_add_to_head", \
	"soft_ring_add_continue", \
	"soft_ring_free_pool_empty", \
	"mimo_ps_mode_switch", \
	"auto_cca_state", \
	"auto_cca_th", \
	"auto_cca_spre", \
	"auto_cca_intf", \
	"total_dmem_alloc", \
	"total_dram_alloc", \
	"dmem_alloc_fails", \
	"dram_alloc_fails", \
	"total_dmem_free", \
	"total_dram_free", \
	"rx_bw_80", \
	"rx_bw_40", \
	"rx_bw_20", \
	"rx_wmm_ps_trigger", \
	"rx_wmm_ps_set", \
	"rx_wmm_ps_reset", \
	"rx_intr_next_ptr_0", \
	"rx_hbm_pool_depleted", \
	"rxq_intr[0]", \
	"rxq_intr[1]", \
	"rxq_intr[2]", \
	"rxq_fill[0]", \
	"rxq_fill[1]", \
	"rxq_fill[2]", \
	"rxq_nobuf[0]", \
	"rxq_nobuf[1]", \
	"rxq_nobuf[2]", \
	"rxq_stop[0]", \
	"rxq_stop[1]", \
	"rxq_stop[2]", \
	"rxq_pkt[0]", \
	"rxq_pkt[1]", \
	"rxq_pkt[2]", \
	"rxq_bad_status[0]", \
	"rxq_bad_status[1]", \
	"rxq_bad_status[2]", \
	"rxq_pkt_oversize[0]", \
	"rxq_pkt_oversize[1]", \
	"rxq_pkt_oversize[2]", \
	"rxq_pkt_delivered[0]", \
	"rxq_pkt_delivered[1]", \
	"rxq_pkt_delivered[2]", \
	"rxq_status_hole_chk_num[0]", \
	"rxq_status_hole_chk_num[1]", \
	"rxq_status_hole_chk_num[2]", \
	"rxq_status_hole_chk_step_sum[0]", \
	"rxq_status_hole_chk_step_sum[1]", \
	"rxq_status_hole_chk_step_sum[2]", \
	"rxq_status_hole_chk_step_max[0]", \
	"rxq_status_hole_chk_step_max[1]", \
	"rxq_status_hole_chk_step_max[2]", \
	"rxq_status_hole[0]", \
	"rxq_status_hole[1]", \
	"rxq_status_hole[2]", \
	"rxq_status_hole_max_size[0]", \
	"rxq_status_hole_max_size[1]", \
	"rxq_status_hole_max_size[2]", \
	"rxq_process_max[0]", \
	"rxq_process_max[1]", \
	"rxq_process_max[2]", \
	"rxq_process_sum[0]", \
	"rxq_process_sum[1]", \
	"rxq_process_sum[2]", \
	"rxq_process_num[0]", \
	"rxq_process_num[1]", \
	"rxq_process_num[2]", \
	"rxq_process_limited[0]", \
	"rxq_process_limited[1]", \
	"rxq_process_limited[2]", \
	"rxq_desc_chain_empty[0]", \
	"rxq_desc_chain_empty[1]", \
	"rxq_desc_chain_empty[2]", \
	"rx_data_last_seqfrag", \
	"rx_data_last_ip_id", \
	"rx_opmode_notify", \
	"rx_frag_drop", \
	"accel_l2_ext_filter", \
	"accel_mc_send_l2_ext_filter", \
	"accel_mc_drop_l2_ext_filter", \
	"rx_stale_nc_reset", \
	"rx_node_deleting", \
	"rx_frame_addressed_to_wrong_bss", \
	"tqe_push_limit_max", \
	"vm_sta_cnt", \
	"vm_rx_pkt_cnt", \
	"rx_decap_snap_drop", \
	"rx_replay_attack_drop", \
	"bb_calib_in_prog", \
	"bb_calib_in_prog_wait_timeout", \
}

enum muc_stats_rx_type {
	MUC_STATS_RX_TYPE_RXDESC_POP_FROM_HOST, 
	MUC_STATS_RX_TYPE_RXDESC_GET_FROM_QUEUE, 
	MUC_STATS_RX_TYPE_RXDESC_PUSH_TO_HOST, 
	MUC_STATS_RX_TYPE_RXDESC_NON_AGGR_PUSH_TO_HOST, 
	MUC_STATS_RX_TYPE_RXDESC_FLUSH_TO_HOST, 
	MUC_STATS_RX_TYPE_RXDESC_REUSE_PUSH, 
	MUC_STATS_RX_TYPE_RXDESC_REUSE_POP, 
	MUC_STATS_RX_TYPE_RXDESC_STATUS_BAD_DUR, 
	MUC_STATS_RX_TYPE_RXDESC_STATUS_BAD_LEN, 
	MUC_STATS_RX_TYPE_RXDESC_STATUS_CRC_ERR, 
	MUC_STATS_RX_TYPE_RXDESC_STATUS_CMIC_ERR, 
	MUC_STATS_RX_TYPE_RXDESC_STATUS_CMIC_NO_CRC_ERR, 
	MUC_STATS_RX_TYPE_RXDESC_STATUS_RETRY, 
	MUC_STATS_RX_TYPE_AGG_STORED, 
	MUC_STATS_RX_TYPE_AGG_DUPLICATE, 
	MUC_STATS_RX_TYPE_ACCEL_MPDU, 
	MUC_STATS_RX_TYPE_ACCEL_MSDU, 
	MUC_STATS_RX_TYPE_ACCEL_FWT_LU_TIMEOUT, 
	MUC_STATS_RX_TYPE_ACCEL_MCAST_SEND, 
	MUC_STATS_RX_TYPE_ACCEL_MCAST_DROP, 
	MUC_STATS_RX_TYPE_ACCEL_NO_MATCH, 
	MUC_STATS_RX_TYPE_ACCEL_DROP, 
	MUC_STATS_RX_TYPE_ACCEL_ERR, 
	MUC_STATS_RX_TYPE_RATE_TRAIN_CHK, 
	MUC_STATS_RX_TYPE_RATE_TRAIN_ERR, 
	MUC_STATS_RX_TYPE_RATE_TRAIN_DELAY, 
	MUC_STATS_RX_TYPE_RATE_TRAIN_NONE, 
	MUC_STATS_RX_TYPE_RATE_TRAIN_HASH_BAD, 
	MUC_STATS_RX_TYPE_RATE_TRAIN_HASH_GOOD, 
	MUC_STATS_RX_TYPE_AGG_OLDPKTS, 
	MUC_STATS_RX_TYPE_AGG_VERY_OLDPKTS, 
	MUC_STATS_RX_TYPE_AGG_EVICT_IN_ORDER, 
	MUC_STATS_RX_TYPE_AGG_EVICT_IN_MOVE, 
	MUC_STATS_RX_TYPE_AGG_EVICT_EMPTY, 
	MUC_STATS_RX_TYPE_AGG_TIMEOUT, 
	MUC_STATS_RX_TYPE_AGG_RXWIN_RESET, 
	MUC_STATS_RX_TYPE_RX_QNUM_ERR, 
	MUC_STATS_RX_TYPE_RX_MGMT, 
	MUC_STATS_RX_TYPE_RX_CTRL, 
	MUC_STATS_RX_TYPE_RX_PSPOLL, 
	MUC_STATS_RX_TYPE_RX_PWR_MGMT, 
	MUC_STATS_RX_TYPE_RX_DELBA, 
	MUC_STATS_RX_TYPE_RX_PWR_MGMT_SET, 
	MUC_STATS_RX_TYPE_RX_PWR_MGMT_RESET, 
	MUC_STATS_RX_TYPE_RX_DESC_UNDERFLOW, 
	MUC_STATS_RX_TYPE_RX_DESC_LINKERR, 
	MUC_STATS_RX_TYPE_RX_NOTIFY, 
	MUC_STATS_RX_TYPE_RX_DF_NUMELEMS, 
	MUC_STATS_RX_TYPE_LAST_RECV_SEQ, 
	MUC_STATS_RX_TYPE_RX_NODE_NOT_FOUND, 
	MUC_STATS_RX_TYPE_RX_DUPLICATE, 
	MUC_STATS_RX_TYPE_RX_11N_NDP, 
	MUC_STATS_RX_TYPE_RX_11AC_NDP, 
	MUC_STATS_RX_TYPE_RX_NDP_INV_SLOT, 
	MUC_STATS_RX_TYPE_RX_NDP_INV_BW, 
	MUC_STATS_RX_TYPE_RX_11N_NDP_NO_CAPT, 
	MUC_STATS_RX_TYPE_RX_NDP_SW_PROCESSED, 
	MUC_STATS_RX_TYPE_RX_NDP_LOCKUP, 
	MUC_STATS_RX_TYPE_RX_11N_BF_ACT, 
	MUC_STATS_RX_TYPE_RX_11AC_BF_ACT, 
	MUC_STATS_RX_TYPE_RX_BF_ACT_INV_SLOT, 
	MUC_STATS_RX_TYPE_RX_CSI_DATA_PROCESSED, 
	MUC_STATS_RX_TYPE_RX_CSI_DATA_NO_CAPT, 
	MUC_STATS_RX_TYPE_RX_CSI_DATA_UNLOCK, 
	MUC_STATS_RX_TYPE_RX_CSI_JIFF_UNLOCK, 
	MUC_STATS_RX_TYPE_RX_AMSDU, 
	MUC_STATS_RX_TYPE_RX_DATA, 
	MUC_STATS_RX_TYPE_PREV_RX_DATA, 
	MUC_STATS_RX_TYPE_RX_RECV_QNULL, 
	MUC_STATS_RX_TYPE_RX_RECV_ACT, 
	MUC_STATS_RX_TYPE_RX_RECV_BCN, 
	MUC_STATS_RX_TYPE_RX_RECV_AUTH, 
	MUC_STATS_RX_TYPE_RX_RECV_ASSOC_REQ, 
	MUC_STATS_RX_TYPE_RX_RECV_ASSOC_RES, 
	MUC_STATS_RX_TYPE_RX_RECV_DEAUTH, 
	MUC_STATS_RX_TYPE_RX_RECV_DISASSOC, 
	MUC_STATS_RX_TYPE_RX_MCS_GT_76, 
	MUC_STATS_RX_TYPE_TKIP_KEYS, 
	MUC_STATS_RX_TYPE_RX_TKIP_MIC_ERR, 
	MUC_STATS_RX_TYPE_ICV_ERRS, 
	MUC_STATS_RX_TYPE_TMIC_ERRS, 
	MUC_STATS_RX_TYPE_CMIC_ERRS, 
	MUC_STATS_RX_TYPE_CRC_ERRS, 
	MUC_STATS_RX_TYPE_PLCP_ERRS, 
	MUC_STATS_RX_TYPE_BA_TX, 
	MUC_STATS_RX_TYPE_BA_RX, 
	MUC_STATS_RX_TYPE_BA_RX_FAIL, 
	MUC_STATS_RX_TYPE_SEC_OFLOW, 
	MUC_STATS_RX_TYPE_STR_OFLOW, 
	MUC_STATS_RX_TYPE_OFLOW_FIXUP_TIMEOUT, 
	MUC_STATS_RX_TYPE_RXDONE_INTR, 
	MUC_STATS_RX_TYPE_RXTYPEDONE_INTR, 
	MUC_STATS_RX_TYPE_IPC_A2M_INTR, 
	MUC_STATS_RX_TYPE_TQE_INTR, 
	MUC_STATS_RX_TYPE_TQE_IN_PORT_LHOST, 
	MUC_STATS_RX_TYPE_TQE_IN_PORT_BAD, 
	MUC_STATS_RX_TYPE_TQE_A2M_TYPE_TXFB, 
	MUC_STATS_RX_TYPE_TQE_A2M_TYPE_RXPKT, 
	MUC_STATS_RX_TYPE_TQE_A2M_TYPE_UNKNOWN, 
	MUC_STATS_RX_TYPE_TQE_RESCHEDULE_TASK, 
	MUC_STATS_RX_TYPE_TQE_DESC_UNOWNED, 
	MUC_STATS_RX_TYPE_BB_INTR, 
	MUC_STATS_RX_TYPE_BB_IRQ_DLEAF_OFLOW, 
	MUC_STATS_RX_TYPE_BB_IRQ_LEAF_UFLOW, 
	MUC_STATS_RX_TYPE_BB_IRQ_LEAF_LDPC_UFLOW, 
	MUC_STATS_RX_TYPE_BB_IRQ_TX_TD_OFLOW_INTR, 
	MUC_STATS_RX_TYPE_BB_IRQ_TX_TD_UFLOW_INTR, 
	MUC_STATS_RX_TYPE_BB_IRQ_RX_SM_WDG_INTR, 
	MUC_STATS_RX_TYPE_BB_IRQ_RX_LONG_DUR, 
	MUC_STATS_RX_TYPE_BB_IRQ_RX_LONG_DUR_11AC, 
	MUC_STATS_RX_TYPE_BB_IRQ_RX_LONG_DUR_11N, 
	MUC_STATS_RX_TYPE_BB_IRQ_RX_LONG_DUR_11N_QTN, 
	MUC_STATS_RX_TYPE_BB_IRQ_RX_SYM_EXCEED_RST, 
	MUC_STATS_RX_TYPE_BB_IRQ_TX_SM_WDG_INTR, 
	MUC_STATS_RX_TYPE_BB_IRQ_MAIN_SM_WDG_INTR, 
	MUC_STATS_RX_TYPE_BB_IRQ_HREADY_WDG_INTR, 
	MUC_STATS_RX_TYPE_MAC_IRQ_RX_SEC_BUFF_OFLOW, 
	MUC_STATS_RX_TYPE_MAC_IRQ_RX_STRQ_OFLOW, 
	MUC_STATS_RX_TYPE_MAC_IRQ_RX_BB_UFLOW_INTR, 
	MUC_STATS_RX_TYPE_MAC_IRQ_RX_BB_OFLOW_INTR, 
	MUC_STATS_RX_TYPE_BB_IRQ_HREADY_WDG_RESET, 
	MUC_STATS_RX_TYPE_SRESET_WDG_BEGIN, 
	MUC_STATS_RX_TYPE_SRESET_WDG_END, 
	MUC_STATS_RX_TYPE_SRESET_WDG_IN_PLACE, 
	MUC_STATS_RX_TYPE_SRESET_WDG_TX_BEACON_HANG, 
	MUC_STATS_RX_TYPE_SRESET_WDG_TX_HANG, 
	MUC_STATS_RX_TYPE_SRESET_WDG_TX_HANG_SEC_CCA, 
	MUC_STATS_RX_TYPE_SRESET_WDG_PM_CORRUPT, 
	MUC_STATS_RX_TYPE_SRESET_WDG_TCM_CORRUPT, 
	MUC_STATS_RX_TYPE_SRESET_WDG_RX_DONE, 
	MUC_STATS_RX_TYPE_SRESET_WDG_IN_PLACE_TRY, 
	MUC_STATS_RX_TYPE_SRESET_WDG_TASKLET_SCHED_1, 
	MUC_STATS_RX_TYPE_SRESET_WDG_TASKLET_SCHED_2, 
	MUC_STATS_RX_TYPE_SRESET_TASKLET_SCHED, 
	MUC_STATS_RX_TYPE_SRESET_TASKLET_BEGIN, 
	MUC_STATS_RX_TYPE_SRESET_TASKLET_END, 
	MUC_STATS_RX_TYPE_HRESET_REQ, 
	MUC_STATS_RX_TYPE_SRESET_BEGIN, 
	MUC_STATS_RX_TYPE_SRESET_END, 
	MUC_STATS_RX_TYPE_SRESET_DMA_RX_INPROG, 
	MUC_STATS_RX_TYPE_SRESET_DMA_TX_INPROG, 
	MUC_STATS_RX_TYPE_SRESET_DMA_RX_MAX_WAIT, 
	MUC_STATS_RX_TYPE_SRESET_DMA_TX_MAX_WAIT, 
	MUC_STATS_RX_TYPE_SRESET_DMA_TX_HANG, 
	MUC_STATS_RX_TYPE_SRESET_DMA_RX_HANG, 
	MUC_STATS_RX_TYPE_SRESET_DMA_RX_WAIT_TIMEOUT, 
	MUC_STATS_RX_TYPE_SRESET_DMA_TX_WAIT_TIMEOUT, 
	MUC_STATS_RX_TYPE_SRESET_DROP_NOT_VALID, 
	MUC_STATS_RX_TYPE_SRESET_DROP_BAD_ADDR, 
	MUC_STATS_RX_TYPE_RF_CMPVTUNE_OUT, 
	MUC_STATS_RX_TYPE_RF_CAL_FREQ, 
	MUC_STATS_RX_TYPE_AC_MAX, 
	MUC_STATS_RX_TYPE_AC_MIN, 
	MUC_STATS_RX_TYPE_AC_CUR, 
	MUC_STATS_RX_TYPE_AC_ADJ, 
	MUC_STATS_RX_TYPE_RX_GAIN, 
	MUC_STATS_RX_TYPE_RD_CACHE_INDX, 
	MUC_STATS_RX_TYPE_LOGGER_SRESET_WMAC1_DMA_RX_INPROG, 
	MUC_STATS_RX_TYPE_LOGGER_SRESET_WMAC1_DMA_TX_INPROG, 
	MUC_STATS_RX_TYPE_LOGGER_SRESET_WMAC1_DMA_RX_MAX_WAIT, 
	MUC_STATS_RX_TYPE_LOGGER_SRESET_WMAC1_DMA_TX_MAX_WAIT, 
	MUC_STATS_RX_TYPE_LOGGER_SRESET_WMAC1_DMA_TX_HANG, 
	MUC_STATS_RX_TYPE_LOGGER_SRESET_WMAC1_DMA_RX_HANG, 
	MUC_STATS_RX_TYPE_LOGGER_SRESET_WMAC1_DMA_RX_WAIT_TIMEOUT, 
	MUC_STATS_RX_TYPE_LOGGER_SRESET_WMAC1_DMA_TX_WAIT_TIMEOUT, 
	MUC_STATS_RX_TYPE_MU_RX_PKT, 
	MUC_STATS_RX_TYPE_PDUTY_SLEEP, 
	MUC_STATS_RX_TYPE_PDUTY_RXOFF, 
	MUC_STATS_RX_TYPE_PDUTY_PERIOD, 
	MUC_STATS_RX_TYPE_PDUTY_PCT, 
	MUC_STATS_RX_TYPE_SOFT_RING_PUSH_TO_TQE, 
	MUC_STATS_RX_TYPE_SOFT_RING_EMPTY, 
	MUC_STATS_RX_TYPE_SOFT_RING_NOT_EMPTY, 
	MUC_STATS_RX_TYPE_SOFT_RING_ADD_FORCE, 
	MUC_STATS_RX_TYPE_SOFT_RING_ADD_TO_HEAD, 
	MUC_STATS_RX_TYPE_SOFT_RING_ADD_CONTINUE, 
	MUC_STATS_RX_TYPE_SOFT_RING_FREE_POOL_EMPTY, 
	MUC_STATS_RX_TYPE_MIMO_PS_MODE_SWITCH, 
	MUC_STATS_RX_TYPE_AUTO_CCA_STATE, 
	MUC_STATS_RX_TYPE_AUTO_CCA_TH, 
	MUC_STATS_RX_TYPE_AUTO_CCA_SPRE, 
	MUC_STATS_RX_TYPE_AUTO_CCA_INTF, 
	MUC_STATS_RX_TYPE_TOTAL_DMEM_ALLOC, 
	MUC_STATS_RX_TYPE_TOTAL_DRAM_ALLOC, 
	MUC_STATS_RX_TYPE_DMEM_ALLOC_FAILS, 
	MUC_STATS_RX_TYPE_DRAM_ALLOC_FAILS, 
	MUC_STATS_RX_TYPE_TOTAL_DMEM_FREE, 
	MUC_STATS_RX_TYPE_TOTAL_DRAM_FREE, 
	MUC_STATS_RX_TYPE_RX_BW_80, 
	MUC_STATS_RX_TYPE_RX_BW_40, 
	MUC_STATS_RX_TYPE_RX_BW_20, 
	MUC_STATS_RX_TYPE_RX_WMM_PS_TRIGGER, 
	MUC_STATS_RX_TYPE_RX_WMM_PS_SET, 
	MUC_STATS_RX_TYPE_RX_WMM_PS_RESET, 
	MUC_STATS_RX_TYPE_RX_INTR_NEXT_PTR_0, 
	MUC_STATS_RX_TYPE_RX_HBM_POOL_DEPLETED, 
	MUC_STATS_RX_TYPE_RXQ_INTR_0, 
	MUC_STATS_RX_TYPE_RXQ_INTR_1, 
	MUC_STATS_RX_TYPE_RXQ_INTR_2, 
	MUC_STATS_RX_TYPE_RXQ_FILL_0, 
	MUC_STATS_RX_TYPE_RXQ_FILL_1, 
	MUC_STATS_RX_TYPE_RXQ_FILL_2, 
	MUC_STATS_RX_TYPE_RXQ_NOBUF_0, 
	MUC_STATS_RX_TYPE_RXQ_NOBUF_1, 
	MUC_STATS_RX_TYPE_RXQ_NOBUF_2, 
	MUC_STATS_RX_TYPE_RXQ_STOP_0, 
	MUC_STATS_RX_TYPE_RXQ_STOP_1, 
	MUC_STATS_RX_TYPE_RXQ_STOP_2, 
	MUC_STATS_RX_TYPE_RXQ_PKT_0, 
	MUC_STATS_RX_TYPE_RXQ_PKT_1, 
	MUC_STATS_RX_TYPE_RXQ_PKT_2, 
	MUC_STATS_RX_TYPE_RXQ_BAD_STATUS_0, 
	MUC_STATS_RX_TYPE_RXQ_BAD_STATUS_1, 
	MUC_STATS_RX_TYPE_RXQ_BAD_STATUS_2, 
	MUC_STATS_RX_TYPE_RXQ_PKT_OVERSIZE_0, 
	MUC_STATS_RX_TYPE_RXQ_PKT_OVERSIZE_1, 
	MUC_STATS_RX_TYPE_RXQ_PKT_OVERSIZE_2, 
	MUC_STATS_RX_TYPE_RXQ_PKT_DELIVERED_0, 
	MUC_STATS_RX_TYPE_RXQ_PKT_DELIVERED_1, 
	MUC_STATS_RX_TYPE_RXQ_PKT_DELIVERED_2, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_CHK_NUM_0, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_CHK_NUM_1, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_CHK_NUM_2, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_CHK_STEP_SUM_0, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_CHK_STEP_SUM_1, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_CHK_STEP_SUM_2, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_CHK_STEP_MAX_0, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_CHK_STEP_MAX_1, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_CHK_STEP_MAX_2, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_0, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_1, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_2, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_MAX_SIZE_0, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_MAX_SIZE_1, 
	MUC_STATS_RX_TYPE_RXQ_STATUS_HOLE_MAX_SIZE_2, 
	MUC_STATS_RX_TYPE_RXQ_PROCESS_MAX_0, 
	MUC_STATS_RX_TYPE_RXQ_PROCESS_MAX_1, 
	MUC_STATS_RX_TYPE_RXQ_PROCESS_MAX_2, 
	MUC_STATS_RX_TYPE_RXQ_PROCESS_SUM_0, 
	MUC_STATS_RX_TYPE_RXQ_PROCESS_SUM_1, 
	MUC_STATS_RX_TYPE_RXQ_PROCESS_SUM_2, 
	MUC_STATS_RX_TYPE_RXQ_PROCESS_NUM_0, 
	MUC_STATS_RX_TYPE_RXQ_PROCESS_NUM_1, 
	MUC_STATS_RX_TYPE_RXQ_PROCESS_NUM_2, 
	MUC_STATS_RX_TYPE_RXQ_PROCESS_LIMITED_0, 
	MUC_STATS_RX_TYPE_RXQ_PROCESS_LIMITED_1, 
	MUC_STATS_RX_TYPE_RXQ_PROCESS_LIMITED_2, 
	MUC_STATS_RX_TYPE_RXQ_DESC_CHAIN_EMPTY_0, 
	MUC_STATS_RX_TYPE_RXQ_DESC_CHAIN_EMPTY_1, 
	MUC_STATS_RX_TYPE_RXQ_DESC_CHAIN_EMPTY_2, 
	MUC_STATS_RX_TYPE_RX_DATA_LAST_SEQFRAG, 
	MUC_STATS_RX_TYPE_RX_DATA_LAST_IP_ID, 
	MUC_STATS_RX_TYPE_RX_OPMODE_NOTIFY, 
	MUC_STATS_RX_TYPE_RX_FRAG_DROP, 
	MUC_STATS_RX_TYPE_ACCEL_L2_EXT_FILTER, 
	MUC_STATS_RX_TYPE_ACCEL_MC_SEND_L2_EXT_FILTER, 
	MUC_STATS_RX_TYPE_ACCEL_MC_DROP_L2_EXT_FILTER, 
	MUC_STATS_RX_TYPE_RX_STALE_NC_RESET, 
	MUC_STATS_RX_TYPE_RX_NODE_DELETING, 
	MUC_STATS_RX_TYPE_RX_FRAME_ADDRESSED_TO_WRONG_BSS, 
	MUC_STATS_RX_TYPE_TQE_PUSH_LIMIT_MAX, 
	MUC_STATS_RX_TYPE_VM_STA_CNT, 
	MUC_STATS_RX_TYPE_VM_RX_PKT_CNT, 
	MUC_STATS_RX_TYPE_RX_DECAP_SNAP_DROP, 
	MUC_STATS_RX_TYPE_RX_REPLAY_ATTACK_DROP, 
	MUC_STATS_RX_TYPE_BB_CALIB_IN_PROG, 
	MUC_STATS_RX_TYPE_BB_CALIB_IN_PROG_WAIT_TIMEOUT, 
};

#define MUC_PTA_STATS_NAMES_TABLE { \
	"pta_intr_cnt", \
	"pta_req_assert_cnt", \
	"pta_req_assert_miss_cnt", \
	"pta_req_deassert_cnt", \
	"pta_gnt_cnt", \
	"pta_gnt_timeout", \
}

enum muc_stats_pta_type {
	MUC_STATS_PTA_TYPE_PTA_INTR_CNT, 
	MUC_STATS_PTA_TYPE_PTA_REQ_ASSERT_CNT, 
	MUC_STATS_PTA_TYPE_PTA_REQ_ASSERT_MISS_CNT, 
	MUC_STATS_PTA_TYPE_PTA_REQ_DEASSERT_CNT, 
	MUC_STATS_PTA_TYPE_PTA_GNT_CNT, 
	MUC_STATS_PTA_TYPE_PTA_GNT_TIMEOUT, 
};
