/****************************************************************************
*
* Copyright (c) 2017  Quantenna Communications, Inc.
*
* Permission to use, copy, modify, and/or distribute this software for any
* purpose with or without fee is hereby granted, provided that the above
* copyright notice and this permission notice appear in all copies.
*
* THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
* WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
* MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
* SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER
* RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
* NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE
* USE OR PERFORMANCE OF THIS SOFTWARE.
*
*****************************************************************************/

#include <string.h>
#include <strings.h>
#include "qtn_cmd_tokens.h"

struct qtn_token_desc {
	const enum qtn_token tok_id;
	const char *tok_text;
};

static
const struct qtn_token_desc qtn_token_table[] = {
	{QTN_TOK_NAME,         "NAME"},
	{QTN_TOK_PROGRAM,      "PROGRAM"},
	{QTN_TOK_PROG,         "PROG"},
	{QTN_TOK_INTERFACE,    "INTERFACE"},
	{QTN_TOK_TYPE,         "TYPE"},
	{QTN_TOK_SSID,         "SSID"},
	{QTN_TOK_CHANNEL,      "CHANNEL"},
	{QTN_TOK_MODE,         "MODE"},
	{QTN_TOK_WME,          "WME"},
	{QTN_TOK_WMMPS,        "WMMPS"},
	{QTN_TOK_RTS,          "RTS"},
	{QTN_TOK_FRGMNT,       "FRGMNT"},
	{QTN_TOK_PWRSAVE,      "PWRSAVE"},
	{QTN_TOK_BCNINT,       "BCNINT"},
	{QTN_TOK_RADIO,        "RADIO"},
	{QTN_TOK_40_INTOLERANT, "40_INTOLERANT"},
	{QTN_TOK_ADDBA_REJECT,  "ADDBA_REJECT"},
	{QTN_TOK_AMPDU,        "AMPDU"},
	{QTN_TOK_AMPDU_EXP,    "AMPDU_EXP"},
	{QTN_TOK_AMSDU,        "AMSDU"},
	{QTN_TOK_GREENFIELD,   "GREENFIELD"},
	{QTN_TOK_OFFSET,       "OFFSET"},
	{QTN_TOK_MCS_32,       "MCS_32"},
	{QTN_TOK_MCS_FIXEDRATE, "MCS_FIXEDRATE"},
	{QTN_TOK_SPATIAL_RX_STREAM, "SPATIAL_RX_STREAM"},
	{QTN_TOK_SPATIAL_TX_STREAM, "SPATIAL_TX_STREAM"},
	{QTN_TOK_MPDU_MIN_START_SPACING, "MPDU_MIN_START_SPACING"},
	{QTN_TOK_RIFS_TEST,    "RIFS_TEST"},
	{QTN_TOK_SGI20,        "SGI20"},
	{QTN_TOK_STBC_TX,      "STBC_TX"},
	{QTN_TOK_WIDTH,        "WIDTH"},
	{QTN_TOK_WIDTH_SCAN,   "WIDTH_SCAN"},
	{QTN_TOK_CWMIN_VO,     "CWMIN_VO"},
	{QTN_TOK_CWMIN_VI,     "CWMIN_VI"},
	{QTN_TOK_CWMIN_BE,     "CWMIN_BE"},
	{QTN_TOK_CWMIN_BK,     "CWMIN_BK"},
	{QTN_TOK_CWMAX_VO,     "CWMAX_VO"},
	{QTN_TOK_CWMAX_VI,     "CWMAX_VI"},
	{QTN_TOK_CWMAX_BE,     "CWMAX_BE"},
	{QTN_TOK_CWMAX_BK,     "CWMAX_BK"},
	{QTN_TOK_AIFS_VO,      "AIFS_VO"},
	{QTN_TOK_AIFS_VI,      "AIFS_VI"},
	{QTN_TOK_AIFS_BE,      "AIFS_BE"},
	{QTN_TOK_AIFS_BK,      "AIFS_BK"},
	{QTN_TOK_TxOP_VO,      "TxOP_VO"},
	{QTN_TOK_TxOP_VI,      "TxOP_VI"},
	{QTN_TOK_TxOP_BE,      "TxOP_BE"},
	{QTN_TOK_TxOP_BK,      "TxOP_BK"},
	{QTN_TOK_ACM_VO,       "ACM_VO"},
	{QTN_TOK_ACM_VI,       "ACM_VI"},
	{QTN_TOK_ACM_BE,       "ACM_BE"},
	{QTN_TOK_ACM_BK,       "ACM_BK"},
	{QTN_TOK_STA_MAC_ADDRESS, "STA_MAC_ADDRESS"},
	{QTN_TOK_MINORCODE,    "MINORCODE"},
	{QTN_TOK_REGULATORY_MODE, "REGULATORY_MODE"},
	{QTN_TOK_COUNTRY_CODE, "CountryCode"},
	{QTN_TOK_DFS_MODE,     "DFS_MODE"},
	{QTN_TOK_DFS_CHAN,     "DFS_CHAN"},
	{QTN_TOK_NSS_MCS_OPT,  "NSS_MCS_OPT"},
	{QTN_TOK_OPT_MD_NOTIF_IE, "OPT_MD_NOTIF_IE"},
	{QTN_TOK_CHNUM_BAND,   "CHNUM_BAND"},
	{QTN_TOK_TID,          "TID"},
	{QTN_TOK_DEST_MAC,     "DEST_MAC"},
	{QTN_TOK_SUPPLICANT,   "SUPPLICANT"},
	{QTN_TOK_PREAMBLE,     "PREAMBLE"},
	{QTN_TOK_POWERSAVE,    "POWERSAVE"},
	{QTN_TOK_NOACK,        "NOACK"},
	{QTN_TOK_IGNORECHSWITCHPROHIBIT, "IGNORECHSWITCHPROHIBIT"},
	{QTN_TOK_TDLS,         "TDLS"},
	{QTN_TOK_TDLSMODE,     "TDLSMODE"},
	{QTN_TOK_WFDDEVTYPE,   "WFDDEVTYPE"},
	{QTN_TOK_UIBC_GEN,     "UIBC_GEN"},
	{QTN_TOK_UIBC_HID,     "UIBC_HID"},
	{QTN_TOK_UI_INPUT,     "UI_INPUT"},
	{QTN_TOK_UIBC_PREPARE, "UIBC_PREPARE"},
	{QTN_TOK_HDCP,         "HDCP"},
	{QTN_TOK_FRAMESKIP,    "FRAMESKIP"},
	{QTN_TOK_AVCHANGE,     "AVCHANGE"},
	{QTN_TOK_STANDBY,      "STANDBY"},
	{QTN_TOK_INPUTCONTENT, "INPUTCONTENT"},
	{QTN_TOK_VIDEOFORMAT,  "VIDEOFORMAT"},
	{QTN_TOK_AUDIOFORMAT,  "AUDIOFORMAT"},
	{QTN_TOK_I2C,          "I2C"},
	{QTN_TOK_VIDEORECOVERY, "VIDEORECOVERY"},
	{QTN_TOK_PREFDISPLAY,  "PREFDISPLAY"},
	{QTN_TOK_SERVICEDISCOVERY, "SERVICEDISCOVERY"},
	{QTN_TOK_3DVIDEO,      "3DVIDEO"},
	{QTN_TOK_MULTITXSTREAM, "MULTITXSTREAM"},
	{QTN_TOK_TIMESYNC,     "TIMESYNC"},
	{QTN_TOK_EDID,         "EDID"},
	{QTN_TOK_COUPLEDCAP,   "COUPLEDCAP"},
	{QTN_TOK_OPTIONALFEATURE, "OPTIONALFEATURE"},
	{QTN_TOK_SESSIONAVAILABILITY, "SESSIONAVAILABILITY"},
	{QTN_TOK_DEVICEDISCOVERABILITY, "DEVICEDISCOVERABILITY"},
	{QTN_TOK_WMM,          "WMM"},
	{QTN_TOK_STBC_RX,      "STBC_RX"},
	{QTN_TOK_MCS32,        "MCS32"},
	{QTN_TOK_SMPS,         "SMPS"},
	{QTN_TOK_TXSP_STREAM,  "TXSP_STREAM"},
	{QTN_TOK_RXSP_STREAM,  "RXSP_STREAM"},
	{QTN_TOK_BAND,         "BAND"},
	{QTN_TOK_DYN_BW_SGNL,  "DYN_BW_SGNL"},
	{QTN_TOK_SGI80,        "SGI80"},
	{QTN_TOK_TXBF,         "TXBF"},
	{QTN_TOK_LDPC,         "LDPC"},
	{QTN_TOK_NSS_MCS_CAP,  "NSS_MCS_CAP"},
	{QTN_TOK_TX_LGI_RATE,  "TX_LGI_RATE"},
	{QTN_TOK_ZERO_CRC,     "ZERO_CRC"},
	{QTN_TOK_VHT_TKIP,     "VHT_TKIP"},
	{QTN_TOK_VHT_WEP,      "VHT_WEP"},
	{QTN_TOK_BW_SGNL,      "BW_SGNL"},
	{QTN_TOK_PASSPHRASE,   "PASSPHRASE"},
	{QTN_TOK_KEYMGNT,      "KEYMGNT"},
	{QTN_TOK_KEYMGMTTYPE,  "KEYMGMTTYPE"},
	{QTN_TOK_ENCPTYPE,     "ENCPTYPE"},
	{QTN_TOK_PMF,          "PMF"},
	{QTN_TOK_MICALG,       "MICALG"},
	{QTN_TOK_PREFER,       "PREFER"},
	{QTN_TOK_FRAMENAME,    "FRAMENAME"},
	{QTN_TOK_CHANNEL_WIDTH,"CHANNEL_WIDTH"},
	{QTN_TOK_NSS,          "NSS"},
	{QTN_TOK_BSSID,        "BSSID"},
	{QTN_TOK_MONTH,        "MONTH"},
	{QTN_TOK_DATE,         "DATE"},
	{QTN_TOK_YEAR,         "YEAR"},
	{QTN_TOK_HOURS,        "HOURS"},
	{QTN_TOK_MINUTES,      "MINUTES"},
	{QTN_TOK_SECONDS,      "SECONDS"},
	{QTN_TOK_MAC,          "MAC"},
	{QTN_TOK_MAXSPLENGTH,  "MAXSPLENGTH"},
	{QTN_TOK_ACBE,         "ACBE"},
	{QTN_TOK_ACBK,         "ACBK"},
	{QTN_TOK_ACVI,         "ACVI"},
	{QTN_TOK_ACVO,         "ACVO"},
	{QTN_TOK_MU_TXBF,      "MU_TXBF"},
	{QTN_TOK_RTS_BWS,      "RTS_BWS"},
	{QTN_TOK_ARP,          "ARP"},
	{QTN_TOK_MU_DBG_GROUP_STA0, "MU_DBG_GROUP_STA0"},
	{QTN_TOK_MU_DBG_GROUP_STA1, "MU_DBG_GROUP_STA1"},
	{QTN_TOK_CTS_WIDTH,    "CTS_WIDTH"},
	{QTN_TOK_RTS_FORCE,    "RTS_FORCE"},
	{QTN_TOK_INTERWORKING, "INTERWORKING"},
	{QTN_TOK_ACCS_NET_TYPE, "ACCS_NET_TYPE"},
	{QTN_TOK_INTERNET, "INTERNET"},
	{QTN_TOK_VENUE_GRP, "VENUE_GRP"},
	{QTN_TOK_VENUE_TYPE, "VENUE_TYPE"},
	{QTN_TOK_HESSID, "HESSID"},
	{QTN_TOK_ROAMING_CONS, "ROAMING_CONS"},
	{QTN_TOK_DGAF_DISABLE, "DGAF_DISABLE"},
	{QTN_TOK_ANQP, "ANQP"},
	{QTN_TOK_NET_AUTH_TYPE, "NET_AUTH_TYPE"},
	{QTN_TOK_NAI_REALM_LIST, "NAI_REALM_LIST"},
	{QTN_TOK_DOMAIN_LIST, "DOMAIN_LIST"},
	{QTN_TOK_OPER_NAME, "OPER_NAME"},
	{QTN_TOK_VENUE_NAME, "VENUE_NAME"},
	{QTN_TOK_GAS_CB_DELAY, "GAS_CB_DELAY"},
	{QTN_TOK_MIH, "MIH"},
	{QTN_TOK_L2_TRAFFIC_INSPECT, "L2_TRAFFIC_INSPECT"},
	{QTN_TOK_BCST_UNCST, "BCST_UNCST"},
	{QTN_TOK_PLMN_MCC, "PLMN_MCC"},
	{QTN_TOK_PLMN_MNC, "PLMN_MNC"},
	{QTN_TOK_PROXY_ARP, "PROXY_ARP"},
	{QTN_TOK_WAN_METRICS, "WAN_METRICS"},
	{QTN_TOK_CONN_CAP, "CONN_CAP"},
	{QTN_TOK_IP_ADD_TYPE_AVAIL, "IP_ADD_TYPE_AVAIL"},
	{QTN_TOK_ICMPV4_ECHO, "ICMPV4_ECHO"},
	{QTN_TOK_CHSWITCHMODE, "CHSWITCHMODE"},
	{QTN_TOK_PEER, "PEER"},
	{QTN_TOK_OFFCHNUM, "OFFCHNUM"},
	{QTN_TOK_SECCHOFFSET, "SECCHOFFSET"},
	{QTN_TOK_UAPSD, "UAPSD"},
	{QTN_TOK_WLAN_TAG, "WLAN_TAG"},
	{QTN_TOK_OSU_SERVER_URI, "OSU_SERVER_URI"},
	{QTN_TOK_OSU_SSID, "OSU_SSID"},
	{QTN_TOK_OSU_PROVIDER_LIST, "OSU_PROVIDER_LIST"},
	{QTN_TOK_QOS_MAP_SET, "QoS_MAP_SET"},
	{QTN_TOK_TXBANDWIDTH, "TXBANDWIDTH"},
	{QTN_TOK_IPADDR, "IPADDR"},
	{QTN_TOK_PORT, "PORT"},
	{QTN_TOK_PASSWORD, "PASSWORD"},
	{QTN_TOK_DTIM, "DTIM"},
	{QTN_TOK_PSK, "PSK"},
	{QTN_TOK_WEPKEY, "WEPKEY"},
	{QTN_TOK_ENCRYPT, "ENCRYPT"}
};


#define N_ARRAY(arr)			(sizeof(arr)/sizeof(arr[0]))

enum qtn_token qtn_lookup_token_by_name(const char *name, int len)
{
	int i;

	if (name && *name && (len > 0)) {
		for (i = 0; i < N_ARRAY(qtn_token_table); i++) {
			if (strncasecmp(qtn_token_table[i].tok_text, name, len) == 0)
				if (strlen(qtn_token_table[i].tok_text) == len)
					return qtn_token_table[i].tok_id;
		}
	}

	return (enum qtn_token) 0;
}
